import {Component, OnInit} from '@angular/core';
import {StandingService} from '../services/standing.service';

declare var $: any;

@Component({
  selector: 'app-standings',
  templateUrl: './standings.page.html',
  styleUrls: ['./standings.page.scss'],
})

export class StandingsPage implements OnInit {

  constructor(private service: StandingService) {
  }

  private leagueData: [];
  //   [
  //   {
  //     api: {
  //       results: 1,
  //       standings: [
  //         [
  //           {
  //             rank: '1',
  //             team_id: '530',
  //             teamName: 'Atletico Madrid',
  //             matchsPlayed: '28',
  //             win: '20',
  //             draw: '6',
  //             lose: '2',
  //             goalsFor: '51',
  //             goalsAgainst: '18',
  //             goalsDiff: '+33',
  //             points: '66',
  //             group: 'Primera División',
  //             lastUpdate: '2021-03-21'
  //           },
  //           {
  //             rank: '2',
  //             team_id: '529',
  //             teamName: 'Barcelona',
  //             matchsPlayed: '28',
  //             win: '19',
  //             draw: '5',
  //             lose: '4',
  //             goalsFor: '67',
  //             goalsAgainst: '24',
  //             goalsDiff: '+43',
  //             points: '62',
  //             group: 'Primera División',
  //             lastUpdate: '2021-03-21'
  //           },
  //           {
  //             rank: '3',
  //             team_id: '541',
  //             teamName: 'Real Madrid',
  //             matchsPlayed: '28',
  //             win: '18',
  //             draw: '6',
  //             lose: '4',
  //             goalsFor: '49',
  //             goalsAgainst: '23',
  //             goalsDiff: '+26',
  //             points: '60',
  //             group: 'Primera División',
  //             lastUpdate: '2021-03-21'
  //           },
  //           {
  //             rank: '4',
  //             team_id: '536',
  //             teamName: 'Sevilla',
  //             matchsPlayed: '28',
  //             win: '17',
  //             draw: '4',
  //             lose: '7',
  //             goalsFor: '39',
  //             goalsAgainst: '21',
  //             goalsDiff: '+18',
  //             points: '55',
  //             group: 'Primera División',
  //             lastUpdate: '2021-03-21'
  //           },
  //           {
  //             rank: '5',
  //             team_id: '548',
  //             teamName: 'Real Sociedad',
  //             matchsPlayed: '28',
  //             win: '12',
  //             draw: '9',
  //             lose: '7',
  //             goalsFor: '44',
  //             goalsAgainst: '28',
  //             goalsDiff: '+16',
  //             points: '45',
  //             group: 'Primera División',
  //             lastUpdate: '2021-03-21'
  //           },
  //           {
  //             rank: '6',
  //             team_id: '543',
  //             teamName: 'Real Betis',
  //             matchsPlayed: '28',
  //             win: '14',
  //             draw: '3',
  //             lose: '11',
  //             goalsFor: '38',
  //             goalsAgainst: '41',
  //             goalsDiff: '-3',
  //             points: '45',
  //             group: 'Primera División',
  //             lastUpdate: '2021-03-21'
  //           },
  //           {
  //             rank: '7',
  //             team_id: '533',
  //             teamName: 'Villarreal',
  //             matchsPlayed: '28',
  //             win: '10',
  //             draw: '13',
  //             lose: '5',
  //             goalsFor: '39',
  //             goalsAgainst: '31',
  //             goalsDiff: '+8',
  //             points: '43',
  //             group: 'Primera División',
  //             lastUpdate: '2021-03-21'
  //           },
  //           {
  //             rank: '8',
  //             team_id: '715',
  //             teamName: 'Granada CF',
  //             matchsPlayed: '28',
  //             win: '10',
  //             draw: '6',
  //             lose: '12',
  //             goalsFor: '34',
  //             goalsAgainst: '46',
  //             goalsDiff: '-12',
  //             points: '36',
  //             group: 'Primera División',
  //             lastUpdate: '2021-03-21'
  //           },
  //           {
  //             rank: '9',
  //             team_id: '531',
  //             teamName: 'Athletic Club',
  //             matchsPlayed: '28',
  //             win: '9',
  //             draw: '8',
  //             lose: '11',
  //             goalsFor: '38',
  //             goalsAgainst: '32',
  //             goalsDiff: '+6',
  //             points: '35',
  //             group: 'Primera División',
  //             lastUpdate: '2021-03-21'
  //           },
  //           {
  //             rank: '10',
  //             team_id: '539',
  //             teamName: 'Levante',
  //             matchsPlayed: '28',
  //             win: '8',
  //             draw: '11',
  //             lose: '9',
  //             goalsFor: '36',
  //             goalsAgainst: '37',
  //             goalsDiff: '-1',
  //             points: '35',
  //             group: 'Primera División',
  //             lastUpdate: '2021-03-21'
  //           },
  //           {
  //             rank: '11',
  //             team_id: '538',
  //             teamName: 'Celta Vigo',
  //             matchsPlayed: '28',
  //             win: '8',
  //             draw: '10',
  //             lose: '10',
  //             goalsFor: '35',
  //             goalsAgainst: '43',
  //             goalsDiff: '-8',
  //             points: '34',
  //             group: 'Primera División',
  //             lastUpdate: '2021-03-21'
  //           },
  //           {
  //             rank: '12',
  //             team_id: '532',
  //             teamName: 'Valencia',
  //             matchsPlayed: '28',
  //             win: '8',
  //             draw: '9',
  //             lose: '11',
  //             goalsFor: '34',
  //             goalsAgainst: '38',
  //             goalsDiff: '-4',
  //             points: '33',
  //             group: 'Primera División',
  //             lastUpdate: '2021-03-21'
  //           },
  //           {
  //             rank: '13',
  //             team_id: '727',
  //             teamName: 'Osasuna',
  //             matchsPlayed: '28',
  //             win: '7',
  //             draw: '9',
  //             lose: '12',
  //             goalsFor: '23',
  //             goalsAgainst: '35',
  //             goalsDiff: '-12',
  //             points: '30',
  //             group: 'Primera División',
  //             lastUpdate: '2021-03-21'
  //           },
  //           {
  //             rank: '14',
  //             team_id: '546',
  //             teamName: 'Getafe',
  //             matchsPlayed: '28',
  //             win: '7',
  //             draw: '8',
  //             lose: '13',
  //             goalsFor: '22',
  //             goalsAgainst: '33',
  //             goalsDiff: '-11',
  //             points: '29',
  //             group: 'Primera División',
  //             lastUpdate: '2021-03-21'
  //           },
  //           {
  //             rank: '15',
  //             team_id: '724',
  //             teamName: 'Cadiz',
  //             matchsPlayed: '28',
  //             win: '7',
  //             draw: '8',
  //             lose: '13',
  //             goalsFor: '24',
  //             goalsAgainst: '44',
  //             goalsDiff: '-20',
  //             points: '29',
  //             group: 'Primera División',
  //             lastUpdate: '2021-03-21'
  //           },
  //           {
  //             rank: '16',
  //             team_id: '720',
  //             teamName: 'Valladolid',
  //             matchsPlayed: '28',
  //             win: '5',
  //             draw: '12',
  //             lose: '11',
  //             goalsFor: '26',
  //             goalsAgainst: '38',
  //             goalsDiff: '-12',
  //             points: '27',
  //             group: 'Primera División',
  //             lastUpdate: '2021-03-21'
  //           },
  //           {
  //             rank: '17',
  //             team_id: '797',
  //             teamName: 'Elche',
  //             matchsPlayed: '28',
  //             win: '5',
  //             draw: '10',
  //             lose: '13',
  //             goalsFor: '25',
  //             goalsAgainst: '42',
  //             goalsDiff: '-17',
  //             points: '25',
  //             group: 'Primera División',
  //             lastUpdate: '2021-03-21'
  //           },
  //           {
  //             rank: '18',
  //             team_id: '545',
  //             teamName: 'Eibar',
  //             matchsPlayed: '28',
  //             win: '4',
  //             draw: '11',
  //             lose: '13',
  //             goalsFor: '22',
  //             goalsAgainst: '33',
  //             goalsDiff: '-11',
  //             points: '23',
  //             group: 'Primera División',
  //             lastUpdate: '2021-03-21'
  //           },
  //           {
  //             rank: '19',
  //             team_id: '542',
  //             teamName: 'Alaves',
  //             matchsPlayed: '28',
  //             win: '5',
  //             draw: '8',
  //             lose: '15',
  //             goalsFor: '23',
  //             goalsAgainst: '44',
  //             goalsDiff: '-21',
  //             points: '23',
  //             group: 'Primera División',
  //             lastUpdate: '2021-03-21'
  //           },
  //           {
  //             rank: '20',
  //             team_id: '726',
  //             teamName: 'Huesca',
  //             matchsPlayed: '28',
  //             win: '3',
  //             draw: '12',
  //             lose: '13',
  //             goalsFor: '26',
  //             goalsAgainst: '44',
  //             goalsDiff: '-18',
  //             points: '21',
  //             group: 'Primera División',
  //             lastUpdate: '2021-03-21'
  //           }
  //         ]
  //       ]
  //     }
  //   },
  //   {
  //     api: {
  //       results: 1,
  //       standings: [
  //         [
  //           {
  //             rank: '1',
  //             team_id: '157',
  //             teamName: 'Bayern Munich',
  //             matchsPlayed: '26',
  //             win: '19',
  //             draw: '4',
  //             lose: '3',
  //             goalsFor: '78',
  //             goalsAgainst: '35',
  //             goalsDiff: '+43',
  //             points: '61',
  //             group: 'Bundesliga',
  //             lastUpdate: '2021-03-21'
  //           },
  //           {
  //             rank: '2',
  //             team_id: '173',
  //             teamName: 'RB Leipzig',
  //             matchsPlayed: '26',
  //             win: '17',
  //             draw: '6',
  //             lose: '3',
  //             goalsFor: '48',
  //             goalsAgainst: '21',
  //             goalsDiff: '+27',
  //             points: '57',
  //             group: 'Bundesliga',
  //             lastUpdate: '2021-03-21'
  //           },
  //           {
  //             rank: '3',
  //             team_id: '161',
  //             teamName: 'VfL Wolfsburg',
  //             matchsPlayed: '26',
  //             win: '14',
  //             draw: '9',
  //             lose: '3',
  //             goalsFor: '45',
  //             goalsAgainst: '22',
  //             goalsDiff: '+23',
  //             points: '51',
  //             group: 'Bundesliga',
  //             lastUpdate: '2021-03-21'
  //           },
  //           {
  //             rank: '4',
  //             team_id: '169',
  //             teamName: 'Eintracht Frankfurt',
  //             matchsPlayed: '26',
  //             win: '12',
  //             draw: '11',
  //             lose: '3',
  //             goalsFor: '53',
  //             goalsAgainst: '36',
  //             goalsDiff: '+17',
  //             points: '47',
  //             group: 'Bundesliga',
  //             lastUpdate: '2021-03-21'
  //           },
  //           {
  //             rank: '5',
  //             team_id: '165',
  //             teamName: 'Borussia Dortmund',
  //             matchsPlayed: '26',
  //             win: '13',
  //             draw: '4',
  //             lose: '9',
  //             goalsFor: '54',
  //             goalsAgainst: '37',
  //             goalsDiff: '+17',
  //             points: '43',
  //             group: 'Bundesliga',
  //             lastUpdate: '2021-03-21'
  //           },
  //           {
  //             rank: '6',
  //             team_id: '168',
  //             teamName: 'Bayer Leverkusen',
  //             matchsPlayed: '26',
  //             win: '11',
  //             draw: '7',
  //             lose: '8',
  //             goalsFor: '43',
  //             goalsAgainst: '31',
  //             goalsDiff: '+12',
  //             points: '40',
  //             group: 'Bundesliga',
  //             lastUpdate: '2021-03-21'
  //           },
  //           {
  //             rank: '7',
  //             team_id: '182',
  //             teamName: 'Union Berlin',
  //             matchsPlayed: '26',
  //             win: '9',
  //             draw: '11',
  //             lose: '6',
  //             goalsFor: '40',
  //             goalsAgainst: '32',
  //             goalsDiff: '+8',
  //             points: '38',
  //             group: 'Bundesliga',
  //             lastUpdate: '2021-03-21'
  //           },
  //           {
  //             rank: '8',
  //             team_id: '160',
  //             teamName: 'SC Freiburg',
  //             matchsPlayed: '26',
  //             win: '10',
  //             draw: '7',
  //             lose: '9',
  //             goalsFor: '39',
  //             goalsAgainst: '39',
  //             goalsDiff: '0',
  //             points: '37',
  //             group: 'Bundesliga',
  //             lastUpdate: '2021-03-21'
  //           },
  //           {
  //             rank: '9',
  //             team_id: '172',
  //             teamName: 'VfB Stuttgart',
  //             matchsPlayed: '26',
  //             win: '9',
  //             draw: '9',
  //             lose: '8',
  //             goalsFor: '47',
  //             goalsAgainst: '41',
  //             goalsDiff: '+6',
  //             points: '36',
  //             group: 'Bundesliga',
  //             lastUpdate: '2021-03-21'
  //           },
  //           {
  //             rank: '10',
  //             team_id: '163',
  //             teamName: 'Borussia Monchengladbach',
  //             matchsPlayed: '26',
  //             win: '9',
  //             draw: '9',
  //             lose: '8',
  //             goalsFor: '44',
  //             goalsAgainst: '40',
  //             goalsDiff: '+4',
  //             points: '36',
  //             group: 'Bundesliga',
  //             lastUpdate: '2021-03-21'
  //           },
  //           {
  //             rank: '11',
  //             team_id: '167',
  //             teamName: '1899 Hoffenheim',
  //             matchsPlayed: '26',
  //             win: '8',
  //             draw: '6',
  //             lose: '12',
  //             goalsFor: '40',
  //             goalsAgainst: '45',
  //             goalsDiff: '-5',
  //             points: '30',
  //             group: 'Bundesliga',
  //             lastUpdate: '2021-03-21'
  //           },
  //           {
  //             rank: '12',
  //             team_id: '162',
  //             teamName: 'Werder Bremen',
  //             matchsPlayed: '26',
  //             win: '7',
  //             draw: '9',
  //             lose: '10',
  //             goalsFor: '31',
  //             goalsAgainst: '38',
  //             goalsDiff: '-7',
  //             points: '30',
  //             group: 'Bundesliga',
  //             lastUpdate: '2021-03-21'
  //           },
  //           {
  //             rank: '13',
  //             team_id: '170',
  //             teamName: 'FC Augsburg',
  //             matchsPlayed: '26',
  //             win: '8',
  //             draw: '5',
  //             lose: '13',
  //             goalsFor: '27',
  //             goalsAgainst: '40',
  //             goalsDiff: '-13',
  //             points: '29',
  //             group: 'Bundesliga',
  //             lastUpdate: '2021-03-21'
  //           },
  //           {
  //             rank: '14',
  //             team_id: '159',
  //             teamName: 'Hertha Berlin',
  //             matchsPlayed: '26',
  //             win: '6',
  //             draw: '6',
  //             lose: '14',
  //             goalsFor: '31',
  //             goalsAgainst: '45',
  //             goalsDiff: '-14',
  //             points: '24',
  //             group: 'Bundesliga',
  //             lastUpdate: '2021-03-21'
  //           },
  //           {
  //             rank: '15',
  //             team_id: '164',
  //             teamName: 'FSV Mainz 05',
  //             matchsPlayed: '26',
  //             win: '6',
  //             draw: '6',
  //             lose: '14',
  //             goalsFor: '26',
  //             goalsAgainst: '45',
  //             goalsDiff: '-19',
  //             points: '24',
  //             group: 'Bundesliga',
  //             lastUpdate: '2021-03-21'
  //           },
  //           {
  //             rank: '16',
  //             team_id: '192',
  //             teamName: 'FC Koln',
  //             matchsPlayed: '26',
  //             win: '5',
  //             draw: '8',
  //             lose: '13',
  //             goalsFor: '25',
  //             goalsAgainst: '46',
  //             goalsDiff: '-21',
  //             points: '23',
  //             group: 'Bundesliga',
  //             lastUpdate: '2021-03-21'
  //           },
  //           {
  //             rank: '17',
  //             team_id: '188',
  //             teamName: 'Arminia Bielefeld',
  //             matchsPlayed: '26',
  //             win: '6',
  //             draw: '4',
  //             lose: '16',
  //             goalsFor: '20',
  //             goalsAgainst: '45',
  //             goalsDiff: '-25',
  //             points: '22',
  //             group: 'Bundesliga',
  //             lastUpdate: '2021-03-21'
  //           },
  //           {
  //             rank: '18',
  //             team_id: '174',
  //             teamName: 'FC Schalke 04',
  //             matchsPlayed: '26',
  //             win: '1',
  //             draw: '7',
  //             lose: '18',
  //             goalsFor: '16',
  //             goalsAgainst: '69',
  //             goalsDiff: '-53',
  //             points: '10',
  //             group: 'Bundesliga',
  //             lastUpdate: '2021-03-21'
  //           }
  //         ]
  //       ]
  //     }
  //   },
  //   {
  //     api: {
  //       results: 1,
  //       standings: [
  //         [
  //           {
  //             rank: '1',
  //             team_id: '50',
  //             teamName: 'Manchester City',
  //             matchsPlayed: '30',
  //             win: '22',
  //             draw: '5',
  //             lose: '3',
  //             goalsFor: '64',
  //             goalsAgainst: '21',
  //             goalsDiff: '+43',
  //             points: '71',
  //             group: 'Premier League',
  //             lastUpdate: '2021-03-21'
  //           },
  //           {
  //             rank: '2',
  //             team_id: '33',
  //             teamName: 'Manchester United',
  //             matchsPlayed: '29',
  //             win: '16',
  //             draw: '9',
  //             lose: '4',
  //             goalsFor: '56',
  //             goalsAgainst: '32',
  //             goalsDiff: '+24',
  //             points: '57',
  //             group: 'Premier League',
  //             lastUpdate: '2021-03-21'
  //           },
  //           {
  //             rank: '3',
  //             team_id: '46',
  //             teamName: 'Leicester',
  //             matchsPlayed: '29',
  //             win: '17',
  //             draw: '5',
  //             lose: '7',
  //             goalsFor: '53',
  //             goalsAgainst: '32',
  //             goalsDiff: '+21',
  //             points: '56',
  //             group: 'Premier League',
  //             lastUpdate: '2021-03-21'
  //           },
  //           {
  //             rank: '4',
  //             team_id: '49',
  //             teamName: 'Chelsea',
  //             matchsPlayed: '29',
  //             win: '14',
  //             draw: '9',
  //             lose: '6',
  //             goalsFor: '44',
  //             goalsAgainst: '25',
  //             goalsDiff: '+19',
  //             points: '51',
  //             group: 'Premier League',
  //             lastUpdate: '2021-03-21'
  //           },
  //           {
  //             rank: '5',
  //             team_id: '48',
  //             teamName: 'West Ham',
  //             matchsPlayed: '29',
  //             win: '14',
  //             draw: '7',
  //             lose: '8',
  //             goalsFor: '45',
  //             goalsAgainst: '35',
  //             goalsDiff: '+10',
  //             points: '49',
  //             group: 'Premier League',
  //             lastUpdate: '2021-03-21'
  //           },
  //           {
  //             rank: '6',
  //             team_id: '47',
  //             teamName: 'Tottenham',
  //             matchsPlayed: '29',
  //             win: '14',
  //             draw: '6',
  //             lose: '9',
  //             goalsFor: '49',
  //             goalsAgainst: '30',
  //             goalsDiff: '+19',
  //             points: '48',
  //             group: 'Premier League',
  //             lastUpdate: '2021-03-21'
  //           },
  //           {
  //             rank: '7',
  //             team_id: '40',
  //             teamName: 'Liverpool',
  //             matchsPlayed: '29',
  //             win: '13',
  //             draw: '7',
  //             lose: '9',
  //             goalsFor: '48',
  //             goalsAgainst: '36',
  //             goalsDiff: '+12',
  //             points: '46',
  //             group: 'Premier League',
  //             lastUpdate: '2021-03-21'
  //           },
  //           {
  //             rank: '8',
  //             team_id: '45',
  //             teamName: 'Everton',
  //             matchsPlayed: '28',
  //             win: '14',
  //             draw: '4',
  //             lose: '10',
  //             goalsFor: '40',
  //             goalsAgainst: '37',
  //             goalsDiff: '+3',
  //             points: '46',
  //             group: 'Premier League',
  //             lastUpdate: '2021-03-21'
  //           },
  //           {
  //             rank: '9',
  //             team_id: '42',
  //             teamName: 'Arsenal',
  //             matchsPlayed: '29',
  //             win: '12',
  //             draw: '6',
  //             lose: '11',
  //             goalsFor: '40',
  //             goalsAgainst: '32',
  //             goalsDiff: '+8',
  //             points: '42',
  //             group: 'Premier League',
  //             lastUpdate: '2021-03-21'
  //           },
  //           {
  //             rank: '10',
  //             team_id: '66',
  //             teamName: 'Aston Villa',
  //             matchsPlayed: '28',
  //             win: '12',
  //             draw: '5',
  //             lose: '11',
  //             goalsFor: '39',
  //             goalsAgainst: '30',
  //             goalsDiff: '+9',
  //             points: '41',
  //             group: 'Premier League',
  //             lastUpdate: '2021-03-21'
  //           },
  //           {
  //             rank: '11',
  //             team_id: '63',
  //             teamName: 'Leeds',
  //             matchsPlayed: '29',
  //             win: '12',
  //             draw: '3',
  //             lose: '14',
  //             goalsFor: '45',
  //             goalsAgainst: '47',
  //             goalsDiff: '-2',
  //             points: '39',
  //             group: 'Premier League',
  //             lastUpdate: '2021-03-21'
  //           },
  //           {
  //             rank: '12',
  //             team_id: '52',
  //             teamName: 'Crystal Palace',
  //             matchsPlayed: '29',
  //             win: '10',
  //             draw: '7',
  //             lose: '12',
  //             goalsFor: '31',
  //             goalsAgainst: '47',
  //             goalsDiff: '-16',
  //             points: '37',
  //             group: 'Premier League',
  //             lastUpdate: '2021-03-21'
  //           },
  //           {
  //             rank: '13',
  //             team_id: '39',
  //             teamName: 'Wolves',
  //             matchsPlayed: '29',
  //             win: '9',
  //             draw: '8',
  //             lose: '12',
  //             goalsFor: '28',
  //             goalsAgainst: '38',
  //             goalsDiff: '-10',
  //             points: '35',
  //             group: 'Premier League',
  //             lastUpdate: '2021-03-21'
  //           },
  //           {
  //             rank: '14',
  //             team_id: '41',
  //             teamName: 'Southampton',
  //             matchsPlayed: '29',
  //             win: '9',
  //             draw: '6',
  //             lose: '14',
  //             goalsFor: '36',
  //             goalsAgainst: '51',
  //             goalsDiff: '-15',
  //             points: '33',
  //             group: 'Premier League',
  //             lastUpdate: '2021-03-21'
  //           },
  //           {
  //             rank: '15',
  //             team_id: '44',
  //             teamName: 'Burnley',
  //             matchsPlayed: '29',
  //             win: '8',
  //             draw: '9',
  //             lose: '12',
  //             goalsFor: '22',
  //             goalsAgainst: '37',
  //             goalsDiff: '-15',
  //             points: '33',
  //             group: 'Premier League',
  //             lastUpdate: '2021-03-21'
  //           },
  //           {
  //             rank: '16',
  //             team_id: '51',
  //             teamName: 'Brighton',
  //             matchsPlayed: '29',
  //             win: '7',
  //             draw: '11',
  //             lose: '11',
  //             goalsFor: '32',
  //             goalsAgainst: '36',
  //             goalsDiff: '-4',
  //             points: '32',
  //             group: 'Premier League',
  //             lastUpdate: '2021-03-21'
  //           },
  //           {
  //             rank: '17',
  //             team_id: '34',
  //             teamName: 'Newcastle',
  //             matchsPlayed: '29',
  //             win: '7',
  //             draw: '7',
  //             lose: '15',
  //             goalsFor: '28',
  //             goalsAgainst: '48',
  //             goalsDiff: '-20',
  //             points: '28',
  //             group: 'Premier League',
  //             lastUpdate: '2021-03-21'
  //           },
  //           {
  //             rank: '18',
  //             team_id: '36',
  //             teamName: 'Fulham',
  //             matchsPlayed: '30',
  //             win: '5',
  //             draw: '11',
  //             lose: '14',
  //             goalsFor: '23',
  //             goalsAgainst: '38',
  //             goalsDiff: '-15',
  //             points: '26',
  //             group: 'Premier League',
  //             lastUpdate: '2021-03-21'
  //           },
  //           {
  //             rank: '19',
  //             team_id: '60',
  //             teamName: 'West Brom',
  //             matchsPlayed: '29',
  //             win: '3',
  //             draw: '9',
  //             lose: '17',
  //             goalsFor: '20',
  //             goalsAgainst: '57',
  //             goalsDiff: '-37',
  //             points: '18',
  //             group: 'Premier League',
  //             lastUpdate: '2021-03-21'
  //           },
  //           {
  //             rank: '20',
  //             team_id: '62',
  //             teamName: 'Sheffield Utd',
  //             matchsPlayed: '29',
  //             win: '4',
  //             draw: '2',
  //             lose: '23',
  //             goalsFor: '16',
  //             goalsAgainst: '50',
  //             goalsDiff: '-34',
  //             points: '14',
  //             group: 'Premier League',
  //             lastUpdate: '2021-03-21'
  //           }
  //         ]
  //       ]
  //     }
  //   },
  //   {
  //     api: {
  //       results: 1,
  //       standings: [
  //         [
  //           {
  //             rank: '1',
  //             team_id: '505',
  //             teamName: 'Inter',
  //             matchsPlayed: '27',
  //             win: '20',
  //             draw: '5',
  //             lose: '2',
  //             goalsFor: '65',
  //             goalsAgainst: '26',
  //             goalsDiff: '+39',
  //             points: '65',
  //             group: 'Serie A',
  //             lastUpdate: '2021-03-21'
  //           },
  //           {
  //             rank: '2',
  //             team_id: '489',
  //             teamName: 'AC Milan',
  //             matchsPlayed: '28',
  //             win: '18',
  //             draw: '5',
  //             lose: '5',
  //             goalsFor: '53',
  //             goalsAgainst: '33',
  //             goalsDiff: '+20',
  //             points: '59',
  //             group: 'Serie A',
  //             lastUpdate: '2021-03-21'
  //           },
  //           {
  //             rank: '3',
  //             team_id: '496',
  //             teamName: 'Juventus',
  //             matchsPlayed: '27',
  //             win: '16',
  //             draw: '7',
  //             lose: '4',
  //             goalsFor: '54',
  //             goalsAgainst: '23',
  //             goalsDiff: '+31',
  //             points: '55',
  //             group: 'Serie A',
  //             lastUpdate: '2021-03-21'
  //           },
  //           {
  //             rank: '4',
  //             team_id: '499',
  //             teamName: 'Atalanta',
  //             matchsPlayed: '28',
  //             win: '16',
  //             draw: '7',
  //             lose: '5',
  //             goalsFor: '65',
  //             goalsAgainst: '34',
  //             goalsDiff: '+31',
  //             points: '55',
  //             group: 'Serie A',
  //             lastUpdate: '2021-03-21'
  //           },
  //           {
  //             rank: '5',
  //             team_id: '492',
  //             teamName: 'Napoli',
  //             matchsPlayed: '27',
  //             win: '17',
  //             draw: '2',
  //             lose: '8',
  //             goalsFor: '58',
  //             goalsAgainst: '29',
  //             goalsDiff: '+29',
  //             points: '53',
  //             group: 'Serie A',
  //             lastUpdate: '2021-03-21'
  //           },
  //           {
  //             rank: '6',
  //             team_id: '497',
  //             teamName: 'AS Roma',
  //             matchsPlayed: '28',
  //             win: '15',
  //             draw: '5',
  //             lose: '8',
  //             goalsFor: '51',
  //             goalsAgainst: '42',
  //             goalsDiff: '+9',
  //             points: '50',
  //             group: 'Serie A',
  //             lastUpdate: '2021-03-21'
  //           },
  //           {
  //             rank: '7',
  //             team_id: '487',
  //             teamName: 'Lazio',
  //             matchsPlayed: '27',
  //             win: '15',
  //             draw: '4',
  //             lose: '8',
  //             goalsFor: '43',
  //             goalsAgainst: '37',
  //             goalsDiff: '+6',
  //             points: '49',
  //             group: 'Serie A',
  //             lastUpdate: '2021-03-21'
  //           },
  //           {
  //             rank: '8',
  //             team_id: '488',
  //             teamName: 'Sassuolo',
  //             matchsPlayed: '27',
  //             win: '10',
  //             draw: '9',
  //             lose: '8',
  //             goalsFor: '45',
  //             goalsAgainst: '44',
  //             goalsDiff: '+1',
  //             points: '39',
  //             group: 'Serie A',
  //             lastUpdate: '2021-03-21'
  //           },
  //           {
  //             rank: '9',
  //             team_id: '504',
  //             teamName: 'Verona',
  //             matchsPlayed: '28',
  //             win: '10',
  //             draw: '8',
  //             lose: '10',
  //             goalsFor: '36',
  //             goalsAgainst: '34',
  //             goalsDiff: '+2',
  //             points: '38',
  //             group: 'Serie A',
  //             lastUpdate: '2021-03-21'
  //           },
  //           {
  //             rank: '10',
  //             team_id: '498',
  //             teamName: 'Sampdoria',
  //             matchsPlayed: '28',
  //             win: '10',
  //             draw: '5',
  //             lose: '13',
  //             goalsFor: '38',
  //             goalsAgainst: '42',
  //             goalsDiff: '-4',
  //             points: '35',
  //             group: 'Serie A',
  //             lastUpdate: '2021-03-21'
  //           },
  //           {
  //             rank: '11',
  //             team_id: '500',
  //             teamName: 'Bologna',
  //             matchsPlayed: '28',
  //             win: '9',
  //             draw: '7',
  //             lose: '12',
  //             goalsFor: '39',
  //             goalsAgainst: '44',
  //             goalsDiff: '-5',
  //             points: '34',
  //             group: 'Serie A',
  //             lastUpdate: '2021-03-21'
  //           },
  //           {
  //             rank: '12',
  //             team_id: '494',
  //             teamName: 'Udinese',
  //             matchsPlayed: '28',
  //             win: '8',
  //             draw: '9',
  //             lose: '11',
  //             goalsFor: '30',
  //             goalsAgainst: '36',
  //             goalsDiff: '-6',
  //             points: '33',
  //             group: 'Serie A',
  //             lastUpdate: '2021-03-21'
  //           },
  //           {
  //             rank: '13',
  //             team_id: '495',
  //             teamName: 'Genoa',
  //             matchsPlayed: '28',
  //             win: '7',
  //             draw: '10',
  //             lose: '11',
  //             goalsFor: '30',
  //             goalsAgainst: '40',
  //             goalsDiff: '-10',
  //             points: '31',
  //             group: 'Serie A',
  //             lastUpdate: '2021-03-21'
  //           },
  //           {
  //             rank: '14',
  //             team_id: '502',
  //             teamName: 'Fiorentina',
  //             matchsPlayed: '28',
  //             win: '7',
  //             draw: '8',
  //             lose: '13',
  //             goalsFor: '35',
  //             goalsAgainst: '45',
  //             goalsDiff: '-10',
  //             points: '29',
  //             group: 'Serie A',
  //             lastUpdate: '2021-03-21'
  //           },
  //           {
  //             rank: '15',
  //             team_id: '515',
  //             teamName: 'Spezia',
  //             matchsPlayed: '28',
  //             win: '7',
  //             draw: '8',
  //             lose: '13',
  //             goalsFor: '36',
  //             goalsAgainst: '51',
  //             goalsDiff: '-15',
  //             points: '29',
  //             group: 'Serie A',
  //             lastUpdate: '2021-03-21'
  //           },
  //           {
  //             rank: '16',
  //             team_id: '506',
  //             teamName: 'Benevento',
  //             matchsPlayed: '28',
  //             win: '7',
  //             draw: '8',
  //             lose: '13',
  //             goalsFor: '28',
  //             goalsAgainst: '52',
  //             goalsDiff: '-24',
  //             points: '29',
  //             group: 'Serie A',
  //             lastUpdate: '2021-03-21'
  //           },
  //           {
  //             rank: '17',
  //             team_id: '503',
  //             teamName: 'Torino',
  //             matchsPlayed: '27',
  //             win: '4',
  //             draw: '11',
  //             lose: '12',
  //             goalsFor: '39',
  //             goalsAgainst: '50',
  //             goalsDiff: '-11',
  //             points: '23',
  //             group: 'Serie A',
  //             lastUpdate: '2021-03-21'
  //           },
  //           {
  //             rank: '18',
  //             team_id: '490',
  //             teamName: 'Cagliari',
  //             matchsPlayed: '28',
  //             win: '5',
  //             draw: '7',
  //             lose: '16',
  //             goalsFor: '31',
  //             goalsAgainst: '48',
  //             goalsDiff: '-17',
  //             points: '22',
  //             group: 'Serie A',
  //             lastUpdate: '2021-03-21'
  //           },
  //           {
  //             rank: '19',
  //             team_id: '523',
  //             teamName: 'Parma',
  //             matchsPlayed: '28',
  //             win: '3',
  //             draw: '10',
  //             lose: '15',
  //             goalsFor: '26',
  //             goalsAgainst: '54',
  //             goalsDiff: '-28',
  //             points: '19',
  //             group: 'Serie A',
  //             lastUpdate: '2021-03-21'
  //           },
  //           {
  //             rank: '20',
  //             team_id: '501',
  //             teamName: 'Crotone',
  //             matchsPlayed: '28',
  //             win: '4',
  //             draw: '3',
  //             lose: '21',
  //             goalsFor: '32',
  //             goalsAgainst: '70',
  //             goalsDiff: '-38',
  //             points: '15',
  //             group: 'Serie A',
  //             lastUpdate: '2021-03-21'
  //           }
  //         ]
  //       ]
  //     }
  //   },
  //   {
  //     api: {
  //       results: 1,
  //       standings: [
  //         [
  //           {
  //             rank: '1',
  //             team_id: '85',
  //             teamName: 'Paris Saint Germain',
  //             matchsPlayed: '30',
  //             win: '20',
  //             draw: '3',
  //             lose: '7',
  //             goalsFor: '67',
  //             goalsAgainst: '21',
  //             goalsDiff: '+46',
  //             points: '63',
  //             group: 'Ligue 1',
  //             lastUpdate: '2021-03-21'
  //           },
  //           {
  //             rank: '2',
  //             team_id: '79',
  //             teamName: 'Lille',
  //             matchsPlayed: '30',
  //             win: '18',
  //             draw: '9',
  //             lose: '3',
  //             goalsFor: '50',
  //             goalsAgainst: '19',
  //             goalsDiff: '+31',
  //             points: '63',
  //             group: 'Ligue 1',
  //             lastUpdate: '2021-03-21'
  //           },
  //           {
  //             rank: '3',
  //             team_id: '80',
  //             teamName: 'Lyon',
  //             matchsPlayed: '30',
  //             win: '17',
  //             draw: '9',
  //             lose: '4',
  //             goalsFor: '59',
  //             goalsAgainst: '30',
  //             goalsDiff: '+29',
  //             points: '60',
  //             group: 'Ligue 1',
  //             lastUpdate: '2021-03-21'
  //           },
  //           {
  //             rank: '4',
  //             team_id: '91',
  //             teamName: 'Monaco',
  //             matchsPlayed: '30',
  //             win: '18',
  //             draw: '5',
  //             lose: '7',
  //             goalsFor: '60',
  //             goalsAgainst: '38',
  //             goalsDiff: '+22',
  //             points: '59',
  //             group: 'Ligue 1',
  //             lastUpdate: '2021-03-21'
  //           },
  //           {
  //             rank: '5',
  //             team_id: '116',
  //             teamName: 'Lens',
  //             matchsPlayed: '30',
  //             win: '13',
  //             draw: '9',
  //             lose: '8',
  //             goalsFor: '46',
  //             goalsAgainst: '42',
  //             goalsDiff: '+4',
  //             points: '48',
  //             group: 'Ligue 1',
  //             lastUpdate: '2021-03-21'
  //           },
  //           {
  //             rank: '6',
  //             team_id: '81',
  //             teamName: 'Marseille',
  //             matchsPlayed: '30',
  //             win: '12',
  //             draw: '9',
  //             lose: '9',
  //             goalsFor: '38',
  //             goalsAgainst: '36',
  //             goalsDiff: '+2',
  //             points: '45',
  //             group: 'Ligue 1',
  //             lastUpdate: '2021-03-21'
  //           },
  //           {
  //             rank: '7',
  //             team_id: '94',
  //             teamName: 'Rennes',
  //             matchsPlayed: '30',
  //             win: '12',
  //             draw: '8',
  //             lose: '10',
  //             goalsFor: '37',
  //             goalsAgainst: '33',
  //             goalsDiff: '+4',
  //             points: '44',
  //             group: 'Ligue 1',
  //             lastUpdate: '2021-03-21'
  //           },
  //           {
  //             rank: '8',
  //             team_id: '82',
  //             teamName: 'Montpellier',
  //             matchsPlayed: '30',
  //             win: '12',
  //             draw: '8',
  //             lose: '10',
  //             goalsFor: '48',
  //             goalsAgainst: '49',
  //             goalsDiff: '-1',
  //             points: '44',
  //             group: 'Ligue 1',
  //             lastUpdate: '2021-03-21'
  //           },
  //           {
  //             rank: '9',
  //             team_id: '112',
  //             teamName: 'Metz',
  //             matchsPlayed: '30',
  //             win: '11',
  //             draw: '9',
  //             lose: '10',
  //             goalsFor: '36',
  //             goalsAgainst: '32',
  //             goalsDiff: '+4',
  //             points: '42',
  //             group: 'Ligue 1',
  //             lastUpdate: '2021-03-21'
  //           },
  //           {
  //             rank: '10',
  //             team_id: '77',
  //             teamName: 'Angers',
  //             matchsPlayed: '30',
  //             win: '11',
  //             draw: '7',
  //             lose: '12',
  //             goalsFor: '33',
  //             goalsAgainst: '43',
  //             goalsDiff: '-10',
  //             points: '40',
  //             group: 'Ligue 1',
  //             lastUpdate: '2021-03-21'
  //           },
  //           {
  //             rank: '11',
  //             team_id: '84',
  //             teamName: 'Nice',
  //             matchsPlayed: '30',
  //             win: '11',
  //             draw: '6',
  //             lose: '13',
  //             goalsFor: '39',
  //             goalsAgainst: '41',
  //             goalsDiff: '-2',
  //             points: '39',
  //             group: 'Ligue 1',
  //             lastUpdate: '2021-03-21'
  //           },
  //           {
  //             rank: '12',
  //             team_id: '93',
  //             teamName: 'Reims',
  //             matchsPlayed: '30',
  //             win: '9',
  //             draw: '11',
  //             lose: '10',
  //             goalsFor: '36',
  //             goalsAgainst: '36',
  //             goalsDiff: '0',
  //             points: '38',
  //             group: 'Ligue 1',
  //             lastUpdate: '2021-03-21'
  //           },
  //           {
  //             rank: '13',
  //             team_id: '78',
  //             teamName: 'Bordeaux',
  //             matchsPlayed: '30',
  //             win: '10',
  //             draw: '6',
  //             lose: '14',
  //             goalsFor: '32',
  //             goalsAgainst: '38',
  //             goalsDiff: '-6',
  //             points: '36',
  //             group: 'Ligue 1',
  //             lastUpdate: '2021-03-21'
  //           },
  //           {
  //             rank: '14',
  //             team_id: '106',
  //             teamName: 'Stade Brestois 29',
  //             matchsPlayed: '30',
  //             win: '10',
  //             draw: '5',
  //             lose: '15',
  //             goalsFor: '43',
  //             goalsAgainst: '53',
  //             goalsDiff: '-10',
  //             points: '35',
  //             group: 'Ligue 1',
  //             lastUpdate: '2021-03-21'
  //           },
  //           {
  //             rank: '15',
  //             team_id: '95',
  //             teamName: 'Strasbourg',
  //             matchsPlayed: '30',
  //             win: '9',
  //             draw: '6',
  //             lose: '15',
  //             goalsFor: '37',
  //             goalsAgainst: '44',
  //             goalsDiff: '-7',
  //             points: '33',
  //             group: 'Ligue 1',
  //             lastUpdate: '2021-03-21'
  //           },
  //           {
  //             rank: '16',
  //             team_id: '1063',
  //             teamName: 'Saint Etienne',
  //             matchsPlayed: '30',
  //             win: '8',
  //             draw: '9',
  //             lose: '13',
  //             goalsFor: '30',
  //             goalsAgainst: '46',
  //             goalsDiff: '-16',
  //             points: '33',
  //             group: 'Ligue 1',
  //             lastUpdate: '2021-03-21'
  //           },
  //           {
  //             rank: '17',
  //             team_id: '97',
  //             teamName: 'Lorient',
  //             matchsPlayed: '30',
  //             win: '7',
  //             draw: '8',
  //             lose: '15',
  //             goalsFor: '36',
  //             goalsAgainst: '54',
  //             goalsDiff: '-18',
  //             points: '29',
  //             group: 'Ligue 1',
  //             lastUpdate: '2021-03-21'
  //           },
  //           {
  //             rank: '18',
  //             team_id: '92',
  //             teamName: 'Nimes',
  //             matchsPlayed: '30',
  //             win: '8',
  //             draw: '5',
  //             lose: '17',
  //             goalsFor: '30',
  //             goalsAgainst: '56',
  //             goalsDiff: '-26',
  //             points: '29',
  //             group: 'Ligue 1',
  //             lastUpdate: '2021-03-21'
  //           },
  //           {
  //             rank: '19',
  //             team_id: '83',
  //             teamName: 'Nantes',
  //             matchsPlayed: '30',
  //             win: '5',
  //             draw: '13',
  //             lose: '12',
  //             goalsFor: '31',
  //             goalsAgainst: '46',
  //             goalsDiff: '-15',
  //             points: '28',
  //             group: 'Ligue 1',
  //             lastUpdate: '2021-03-21'
  //           },
  //           {
  //             rank: '20',
  //             team_id: '89',
  //             teamName: 'Dijon',
  //             matchsPlayed: '30',
  //             win: '2',
  //             draw: '9',
  //             lose: '19',
  //             goalsFor: '20',
  //             goalsAgainst: '51',
  //             goalsDiff: '-31',
  //             points: '15',
  //             group: 'Ligue 1',
  //             lastUpdate: '2021-03-21'
  //           }
  //         ]
  //       ]
  //     }
  //   },
  //   {
  //     api: {
  //       results: 1,
  //       standings: [
  //         [
  //           {
  //             rank: '1',
  //             team_id: '549',
  //             teamName: 'Besiktas',
  //             matchsPlayed: '29',
  //             win: '20',
  //             draw: '4',
  //             lose: '5',
  //             goalsFor: '63',
  //             goalsAgainst: '30',
  //             goalsDiff: '+33',
  //             points: '64',
  //             group: 'Süper Lig',
  //             lastUpdate: '2021-03-21'
  //           },
  //           {
  //             rank: '2',
  //             team_id: '645',
  //             teamName: 'Galatasaray',
  //             matchsPlayed: '30',
  //             win: '19',
  //             draw: '4',
  //             lose: '7',
  //             goalsFor: '61',
  //             goalsAgainst: '27',
  //             goalsDiff: '+34',
  //             points: '61',
  //             group: 'Süper Lig',
  //             lastUpdate: '2021-03-21'
  //           },
  //           {
  //             rank: '3',
  //             team_id: '611',
  //             teamName: 'Fenerbahce',
  //             matchsPlayed: '30',
  //             win: '18',
  //             draw: '5',
  //             lose: '7',
  //             goalsFor: '54',
  //             goalsAgainst: '31',
  //             goalsDiff: '+23',
  //             points: '59',
  //             group: 'Süper Lig',
  //             lastUpdate: '2021-03-21'
  //           },
  //           {
  //             rank: '4',
  //             team_id: '998',
  //             teamName: 'Trabzonspor',
  //             matchsPlayed: '30',
  //             win: '16',
  //             draw: '7',
  //             lose: '7',
  //             goalsFor: '39',
  //             goalsAgainst: '30',
  //             goalsDiff: '+9',
  //             points: '55',
  //             group: 'Süper Lig',
  //             lastUpdate: '2021-03-21'
  //           },
  //           {
  //             rank: '5',
  //             team_id: '996',
  //             teamName: 'Alanyaspor',
  //             matchsPlayed: '30',
  //             win: '14',
  //             draw: '7',
  //             lose: '9',
  //             goalsFor: '48',
  //             goalsAgainst: '29',
  //             goalsDiff: '+19',
  //             points: '49',
  //             group: 'Süper Lig',
  //             lastUpdate: '2021-03-21'
  //           },
  //           {
  //             rank: '6',
  //             team_id: '3573',
  //             teamName: 'Gazişehir Gaziantep',
  //             matchsPlayed: '30',
  //             win: '12',
  //             draw: '11',
  //             lose: '7',
  //             goalsFor: '44',
  //             goalsAgainst: '34',
  //             goalsDiff: '+10',
  //             points: '47',
  //             group: 'Süper Lig',
  //             lastUpdate: '2021-03-21'
  //           },
  //           {
  //             rank: '7',
  //             team_id: '3575',
  //             teamName: 'Hatayspor',
  //             matchsPlayed: '29',
  //             win: '13',
  //             draw: '7',
  //             lose: '9',
  //             goalsFor: '48',
  //             goalsAgainst: '36',
  //             goalsDiff: '+12',
  //             points: '46',
  //             group: 'Süper Lig',
  //             lastUpdate: '2021-03-21'
  //           },
  //           {
  //             rank: '8',
  //             team_id: '3589',
  //             teamName: 'Fatih Karagümrük',
  //             matchsPlayed: '30',
  //             win: '12',
  //             draw: '8',
  //             lose: '10',
  //             goalsFor: '46',
  //             goalsAgainst: '38',
  //             goalsDiff: '+8',
  //             points: '44',
  //             group: 'Süper Lig',
  //             lastUpdate: '2021-03-21'
  //           },
  //           {
  //             rank: '9',
  //             team_id: '1002',
  //             teamName: 'Sivasspor',
  //             matchsPlayed: '29',
  //             win: '9',
  //             draw: '13',
  //             lose: '7',
  //             goalsFor: '37',
  //             goalsAgainst: '35',
  //             goalsDiff: '+2',
  //             points: '40',
  //             group: 'Süper Lig',
  //             lastUpdate: '2021-03-21'
  //           },
  //           {
  //             rank: '10',
  //             team_id: '994',
  //             teamName: 'Goztepe',
  //             matchsPlayed: '30',
  //             win: '10',
  //             draw: '9',
  //             lose: '11',
  //             goalsFor: '43',
  //             goalsAgainst: '41',
  //             goalsDiff: '+2',
  //             points: '39',
  //             group: 'Süper Lig',
  //             lastUpdate: '2021-03-21'
  //           },
  //           {
  //             rank: '11',
  //             team_id: '1005',
  //             teamName: 'Antalyaspor',
  //             matchsPlayed: '30',
  //             win: '8',
  //             draw: '15',
  //             lose: '7',
  //             goalsFor: '29',
  //             goalsAgainst: '36',
  //             goalsDiff: '-7',
  //             points: '39',
  //             group: 'Süper Lig',
  //             lastUpdate: '2021-03-21'
  //           },
  //           {
  //             rank: '12',
  //             team_id: '607',
  //             teamName: 'Konyaspor',
  //             matchsPlayed: '29',
  //             win: '9',
  //             draw: '9',
  //             lose: '11',
  //             goalsFor: '35',
  //             goalsAgainst: '35',
  //             goalsDiff: '0',
  //             points: '36',
  //             group: 'Süper Lig',
  //             lastUpdate: '2021-03-21'
  //           },
  //           {
  //             rank: '13',
  //             team_id: '1007',
  //             teamName: 'Rizespor',
  //             matchsPlayed: '29',
  //             win: '8',
  //             draw: '10',
  //             lose: '11',
  //             goalsFor: '36',
  //             goalsAgainst: '47',
  //             goalsDiff: '-11',
  //             points: '34',
  //             group: 'Süper Lig',
  //             lastUpdate: '2021-03-21'
  //           },
  //           {
  //             rank: '14',
  //             team_id: '999',
  //             teamName: 'Yeni Malatyaspor',
  //             matchsPlayed: '29',
  //             win: '7',
  //             draw: '11',
  //             lose: '11',
  //             goalsFor: '37',
  //             goalsAgainst: '41',
  //             goalsDiff: '-4',
  //             points: '32',
  //             group: 'Süper Lig',
  //             lastUpdate: '2021-03-21'
  //           },
  //           {
  //             rank: '15',
  //             team_id: '1004',
  //             teamName: 'Kasimpasa',
  //             matchsPlayed: '30',
  //             win: '8',
  //             draw: '7',
  //             lose: '15',
  //             goalsFor: '33',
  //             goalsAgainst: '47',
  //             goalsDiff: '-14',
  //             points: '31',
  //             group: 'Süper Lig',
  //             lastUpdate: '2021-03-21'
  //           },
  //           {
  //             rank: '16',
  //             team_id: '1001',
  //             teamName: 'Kayserispor',
  //             matchsPlayed: '29',
  //             win: '8',
  //             draw: '7',
  //             lose: '14',
  //             goalsFor: '22',
  //             goalsAgainst: '38',
  //             goalsDiff: '-16',
  //             points: '31',
  //             group: 'Süper Lig',
  //             lastUpdate: '2021-03-21'
  //           },
  //           {
  //             rank: '17',
  //             team_id: '564',
  //             teamName: 'Istanbul Basaksehir',
  //             matchsPlayed: '30',
  //             win: '7',
  //             draw: '9',
  //             lose: '14',
  //             goalsFor: '32',
  //             goalsAgainst: '48',
  //             goalsDiff: '-16',
  //             points: '30',
  //             group: 'Süper Lig',
  //             lastUpdate: '2021-03-21'
  //           },
  //           {
  //             rank: '18',
  //             team_id: '1010',
  //             teamName: 'Ankaragucu',
  //             matchsPlayed: '29',
  //             win: '8',
  //             draw: '5',
  //             lose: '16',
  //             goalsFor: '35',
  //             goalsAgainst: '49',
  //             goalsDiff: '-14',
  //             points: '29',
  //             group: 'Süper Lig',
  //             lastUpdate: '2021-03-21'
  //           },
  //           {
  //             rank: '19',
  //             team_id: '1009',
  //             teamName: 'Erzurum BB',
  //             matchsPlayed: '30',
  //             win: '6',
  //             draw: '9',
  //             lose: '15',
  //             goalsFor: '28',
  //             goalsAgainst: '49',
  //             goalsDiff: '-21',
  //             points: '27',
  //             group: 'Süper Lig',
  //             lastUpdate: '2021-03-21'
  //           },
  //           {
  //             rank: '20',
  //             team_id: '997',
  //             teamName: 'Genclerbirligi',
  //             matchsPlayed: '29',
  //             win: '7',
  //             draw: '6',
  //             lose: '16',
  //             goalsFor: '26',
  //             goalsAgainst: '51',
  //             goalsDiff: '-25',
  //             points: '27',
  //             group: 'Süper Lig',
  //             lastUpdate: '2021-03-21'
  //           },
  //           {
  //             rank: '21',
  //             team_id: '3570',
  //             teamName: 'Denizlispor',
  //             matchsPlayed: '29',
  //             win: '6',
  //             draw: '7',
  //             lose: '16',
  //             goalsFor: '26',
  //             goalsAgainst: '50',
  //             goalsDiff: '-24',
  //             points: '25',
  //             group: 'Süper Lig',
  //             lastUpdate: '2021-03-21'
  //           }
  //         ]
  //       ]
  //     }
  //   },
  //   {
  //     api: {
  //       results: 1,
  //       standings: [
  //         [
  //           {
  //             rank: '1',
  //             team_id: '556',
  //             teamName: 'Qarabag',
  //             matchsPlayed: '20',
  //             win: '12',
  //             draw: '6',
  //             lose: '2',
  //             goalsFor: '46',
  //             goalsAgainst: '13',
  //             goalsDiff: '+33',
  //             points: '42',
  //             group: 'Premyer Liqa',
  //             lastUpdate: '2021-03-14'
  //           },
  //           {
  //             rank: '2',
  //             team_id: '2270',
  //             teamName: 'Neftchi Baku',
  //             matchsPlayed: '20',
  //             win: '13',
  //             draw: '3',
  //             lose: '4',
  //             goalsFor: '30',
  //             goalsAgainst: '19',
  //             goalsDiff: '+11',
  //             points: '42',
  //             group: 'Premyer Liqa',
  //             lastUpdate: '2021-03-14'
  //           },
  //           {
  //             rank: '3',
  //             team_id: '648',
  //             teamName: 'Zira',
  //             matchsPlayed: '20',
  //             win: '7',
  //             draw: '9',
  //             lose: '4',
  //             goalsFor: '24',
  //             goalsAgainst: '21',
  //             goalsDiff: '+3',
  //             points: '30',
  //             group: 'Premyer Liqa',
  //             lastUpdate: '2021-03-14'
  //           },
  //           {
  //             rank: '4',
  //             team_id: '5503',
  //             teamName: 'Sumqayıt',
  //             matchsPlayed: '20',
  //             win: '6',
  //             draw: '8',
  //             lose: '6',
  //             goalsFor: '23',
  //             goalsAgainst: '24',
  //             goalsDiff: '-1',
  //             points: '26',
  //             group: 'Premyer Liqa',
  //             lastUpdate: '2021-03-14'
  //           },
  //           {
  //             rank: '5',
  //             team_id: '627',
  //             teamName: 'Qabala',
  //             matchsPlayed: '20',
  //             win: '5',
  //             draw: '8',
  //             lose: '7',
  //             goalsFor: '18',
  //             goalsAgainst: '28',
  //             goalsDiff: '-10',
  //             points: '23',
  //             group: 'Premyer Liqa',
  //             lastUpdate: '2021-03-14'
  //           },
  //           {
  //             rank: '6',
  //             team_id: '4199',
  //             teamName: 'Səbail',
  //             matchsPlayed: '20',
  //             win: '4',
  //             draw: '6',
  //             lose: '10',
  //             goalsFor: '19',
  //             goalsAgainst: '33',
  //             goalsDiff: '-14',
  //             points: '18',
  //             group: 'Premyer Liqa',
  //             lastUpdate: '2021-03-14'
  //           },
  //           {
  //             rank: '7',
  //             team_id: '666',
  //             teamName: 'Keshla FC',
  //             matchsPlayed: '20',
  //             win: '3',
  //             draw: '8',
  //             lose: '9',
  //             goalsFor: '20',
  //             goalsAgainst: '32',
  //             goalsDiff: '-12',
  //             points: '17',
  //             group: 'Premyer Liqa',
  //             lastUpdate: '2021-03-14'
  //           },
  //           {
  //             rank: '8',
  //             team_id: '13976',
  //             teamName: 'Sabah FA',
  //             matchsPlayed: '20',
  //             win: '4',
  //             draw: '4',
  //             lose: '12',
  //             goalsFor: '19',
  //             goalsAgainst: '29',
  //             goalsDiff: '-10',
  //             points: '16',
  //             group: 'Premyer Liqa',
  //             lastUpdate: '2021-03-14'
  //           }
  //         ]
  //       ]
  //     }
  //   }
  // ];
  leagues = [];
  selectedLeague = 0;

  ngOnInit() {
    this.getData();
    this.initPage();
  }

  getData() {
    this.service.getData().subscribe((data => {
      this.leagueData = data;
      data?.map(league => {
        this.leagues.push(league.api.standings[0][0].group);
      });
    }));
  }

  changeLeague() {
    const selectedLeague = this.selectedLeague;
    $('.league-col').each(function (index, value) {
      $(value).hide();
      if (index === selectedLeague) {
        $(value).show();
      }
    });
  }

  initPage() {
    const leagues = this.leagues;
    this.selectedLeague = this.leagues[0];
    $(document).ready(function () {
      $('.league-col').each(function (index, value) {
        $(value).hide();
        if (index === 0) {
          $(value).show();
          console.log($('#league-select >'));
        }
      });
    });
  }
}
